sylius_core:
    routing:
        %sylius.model.product.class%:
            field: slug
            prefix: /
            defaults:
                controller: sylius.controller.product:showAction
                sylius:
                    template: SyliusWebBundle:Frontend/Product:show.html.twig
                    criteria: {slug: $slug}