parameters:
    netgen.ez_sylius.field_type.syliusproduct.class: Netgen\Bundle\EzSyliusBundle\Core\FieldType\SyliusProduct\Type
    netgen.ez_sylius.field_type.syliusproduct.external_storage.class: Netgen\Bundle\EzSyliusBundle\Core\FieldType\SyliusProduct\SyliusProductStorage
    netgen.ez_sylius.field_type.syliusproduct.storage_gateway.class: Netgen\Bundle\EzSyliusBundle\Core\FieldType\SyliusProduct\SyliusProductStorage\Gateway\LegacyStorage

services:
    netgen.ez_sylius.field_type.syliusproduct:
        class: %netgen.ez_sylius.field_type.syliusproduct.class%
        parent: ezpublish.fieldType
        arguments:
            - @sylius.repository.product
        tags:
            - {name: ezpublish.fieldType, alias: syliusproduct}

    netgen.ez_sylius.field_type.syliusproduct.external_storage:
        class: %netgen.ez_sylius.field_type.syliusproduct.external_storage.class%
        arguments:
            - @sylius.repository.product
            - @sylius.manager.product
            - @ezpublish.api.service.content
            - @sylius.repository.tax_category
            - @ezpublish.locale.converter
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: syliusproduct}

    netgen.ez_sylius.field_type.syliusproduct.storage_gateway:
        class: %netgen.ez_sylius.field_type.syliusproduct.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: syliusproduct, identifier: LegacyStorage}
