parameters:
    netgen.ez_sylius.search.legacy.gateway.sort_clause_handler.common.product_number.class: Netgen\Bundle\EzSyliusBundle\Core\Search\Legacy\Content\Common\Gateway\SortClauseHandler\ProductNumber

services:
    netgen.ez_sylius.search.legacy.gateway.sort_clause_handler.common.product_number:
        class: %netgen.ez_sylius.search.legacy.gateway.sort_clause_handler.common.product_number.class%
        parent: ezpublish.search.legacy.gateway.sort_clause_handler.common.field
        tags:
            - {name: ezpublish.search.legacy.gateway.sort_clause_handler.content}
            - {name: ezpublish.search.legacy.gateway.sort_clause_handler.location}
