parameters:
    netgen.ez_sylius.persistence.legacy.search.gateway.sort_clause_handler.common.product_number.class: Netgen\Bundle\EzSyliusBundle\Core\Persistence\Legacy\Content\Search\Common\Gateway\SortClauseHandler\ProductNumber

services:
    netgen.ez_sylius.persistence.legacy.search.gateway.sort_clause_handler.common.product_number:
        class: %netgen.ez_sylius.persistence.legacy.search.gateway.sort_clause_handler.common.product_number.class%
        parent: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.common.field
        tags:
            - {name: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.content}
            - {name: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.location}
