parameters:
    netgen_ez_sylius.cart_item_resolver.class: Netgen\EzSyliusBundle\Cart\ItemResolver
    netgen_ez_sylius.configuration_factory.class: Sylius\Bundle\ResourceBundle\Controller\Configuration

services:
     netgen_ez_sylius.cart_item_resolver:
         class: %netgen_ez_sylius.cart_item_resolver.class%
         arguments:
             - @ezpublish.api.repository

     netgen_ez_sylius.configuration_factory:
         class: %netgen_ez_sylius.configuration_factory.class%
         factory_service: sylius.controller.configuration_factory
         factory_method: createConfiguration
         arguments:
             - "sylius"
             - "cart"
             - "NetgenEzSyliusBundle:Cart"

     sylius.controller.cart:
         class: %sylius.controller.cart.class%
         arguments:
             - @netgen_ez_sylius.configuration_factory
         calls:
             - [setContainer, [@service_container]]

     gedmo.listener.softdeleteable:
         class: Gedmo\SoftDeleteable\SoftDeleteableListener
         tags:
             - { name: doctrine.event_subscriber, connection: eng_repository_connection }
         calls:
             - [ setAnnotationReader, [ @annotation_reader ] ]


