parameters:
    netgen_ez_sylius.configuration_factory.class: Sylius\Bundle\ResourceBundle\Controller\Configuration
    netgen_ez_sylius.onpublish_slot.class: Netgen\EzSyliusBundle\Core\Slot\CreateSlugOnPublishSlot

services:

     netgen_ez_sylius.configuration_factory:
         class: %netgen_ez_sylius.configuration_factory.class%
         factory_service: sylius.controller.configuration_factory
         factory_method: createConfiguration
         arguments:
             - "sylius"
             - "cart"
             - "NetgenEzSyliusBundle:Cart"

     sylius.controller.cart:
         class: %sylius.controller.cart.class%
         arguments:
             - @netgen_ez_sylius.configuration_factory
         calls:
             - [setContainer, [@service_container]]

     gedmo.listener.softdeleteable:
         class: Gedmo\SoftDeleteable\SoftDeleteableListener
         tags:
             - { name: doctrine.event_subscriber, connection: eng_repository_connection }
         calls:
             - [ setAnnotationReader, [ @annotation_reader ] ]

     sylius.order_processing.inventory_handler:
          class: Netgen\EzSyliusBundle\OrderProcessing\DummyInventoryHandler

     sluggable.listener:
          alias: stof_doctrine_extensions.listener.sluggable

     netgen_ez_sylius.onpublish_slot:
        class: %netgen_ez_sylius.onpublish_slot.class%
        arguments: [ @ezpublish.api.repository, @sylius.repository.product, @sylius.manager.product, %netgen_ez_sylius_class_identifier%, %netgen_ez_sylius.field_definition_identifier_mappings%, @ezpublish.cache_pool.spi.cache.decorator ]
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\PublishVersionSignal }

