parameters:
    netgen.ez_sylius.signalslot.slot.trash.class: Netgen\Bundle\EzSyliusBundle\Core\Slot\TrashSlot
    netgen.ez_sylius.signalslot.slot.untrash.class: Netgen\Bundle\EzSyliusBundle\Core\Slot\UntrashSlot

services:
    netgen.ez_sylius.signalslot.slot.trash:
        class: %netgen.ez_sylius.signalslot.slot.trash.class%
        arguments:
            - @ezpublish.api.repository
            - @doctrine.orm.entity_manager
            - @sylius.repository.product
            - @sylius.manager.product
        tags:
            - { name: ezpublish.api.slot, signal: TrashService\TrashSignal }

    netgen.ez_sylius.signalslot.slot.untrash:
        class: %netgen.ez_sylius.signalslot.slot.untrash.class%
        arguments:
            - @ezpublish.api.repository
            - @doctrine.orm.entity_manager
            - @sylius.repository.product
            - @sylius.manager.product
        tags:
            - { name: ezpublish.api.slot, signal: TrashService\RecoverSignal }
