parameters:
    ezpublish.fieldType.sylius_product.converter.class: Netgen\Bundle\EzSyliusBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\SyliusProductConverter

services:
    ezpublish.fieldType.sylius_product.converter:
        class: %ezpublish.fieldType.sylius_product.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: syliusproduct, lazy: true, callback: "::create"}